### ISSUE TITLE
Include best-attachment link on parent item

### ISSUE THREAD

**Issue by dstillman** [zotero/dataserver#87]
Necessary for a direct link from the items list on web-library

**Comment by dstillman** [comment]
@tnajdek: For specifying this, are we OK with an `attachment` link on the parent, pointing to the API URL of the best attachment and including its content type? The attachment item itself uses `enclosure`. Not that it really matters, but `attachment` is listed as "proposed" on http://microformats.org/wiki/existing-rel-values.

Also, this will list a best attachment even if the file doesn't exist. So, basically, this would determine if a PDF/attachment icon appeared in the items list, but if you clicked on it it still might show a message that the file couldn't be found (as in the client). It would do that by making a request to the provided attachment URI on click and checking for the `enclosure` link (which is to /file/view, but it would append /url). (I think you said you were doing that elsewhere by checking for `md5`/`mtime`, which I think is technically equivalent but a little less proper than using `enclosure`.)

**Comment by tnajdek** [comment]
> are we OK with an attachment link on the parent, pointing to the API URL of the best attachment and including its content type

Just to clarify: that would be an URL of an **attachment item**, accompanied with a content type of the attachment file, e.g.

````json
"attachment": {
    "type": "application/json",
    "attachmentType": "application/pdf",
    "href": "https://api.zotero.org/users/1234567/items/ABCDEFGH"
} 
````

*Please note: I assume we cannot use `type` here to specify attachment content-type because technically `href` is pointing at the attachment item, hence `application/json` is the correct value. `attachmentType` is not ideal, just couldn't think of anything better.*

In this scenario technically we need to make two requests on user interaction, first to fetch that item and check for `enclosure` link as you've described, second to the `/url` endpoint to get a temporary URL which we can then instruct the browser to open in new tab. Practically I believe that first request is redundant as we have all the information to construct the second URL (pointing at `/url` endpoint) and could display an error if that request returns 404.

This is probably the most correct way of doing this and it would work for me.

An alternative would be to include content of `enclosure` of the "best" attachemnt item, verbatim as a value of `attachment` on the parent. It would also work but I think it would be less "correct" approach.

> I think you said you were doing that elsewhere by checking for md5/mtime, which I think is technically equivalent but a little less proper than using enclosure.)

That's correct, I'm checking for presence of md5. I'll revisit that to use the more proper approach.
